/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package coche.crud.sb.model.impl;

import aQute.bnd.annotation.ProviderType;

import coche.crud.sb.model.Coche;
import coche.crud.sb.model.CocheModel;
import coche.crud.sb.model.CocheSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Coche service. Represents a row in the &quot;Coches_Coche&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link CocheModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CocheImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CocheImpl
 * @see Coche
 * @see CocheModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class CocheModelImpl extends BaseModelImpl<Coche> implements CocheModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a coche model instance should use the {@link Coche} interface instead.
	 */
	public static final String TABLE_NAME = "Coches_Coche";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "CocheId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "marca", Types.VARCHAR },
			{ "modelo", Types.VARCHAR },
			{ "precio", Types.DOUBLE }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CocheId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("marca", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("modelo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("precio", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE = "create table Coches_Coche (uuid_ VARCHAR(75) null,CocheId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,marca VARCHAR(75) null,modelo VARCHAR(75) null,precio DOUBLE)";
	public static final String TABLE_SQL_DROP = "drop table Coches_Coche";
	public static final String ORDER_BY_JPQL = " ORDER BY coche.marca ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Coches_Coche.marca ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(coche.crud.sb.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.coche.crud.sb.model.Coche"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(coche.crud.sb.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.coche.crud.sb.model.Coche"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(coche.crud.sb.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.coche.crud.sb.model.Coche"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long UUID_COLUMN_BITMASK = 2L;
	public static final long MARCA_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Coche toModel(CocheSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Coche model = new CocheImpl();

		model.setUuid(soapModel.getUuid());
		model.setCocheId(soapModel.getCocheId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setMarca(soapModel.getMarca());
		model.setModelo(soapModel.getModelo());
		model.setPrecio(soapModel.getPrecio());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Coche> toModels(CocheSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Coche> models = new ArrayList<Coche>(soapModels.length);

		for (CocheSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(coche.crud.sb.service.util.ServiceProps.get(
				"lock.expiration.time.coche.crud.sb.model.Coche"));

	public CocheModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _CocheId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCocheId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _CocheId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Coche.class;
	}

	@Override
	public String getModelClassName() {
		return Coche.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("CocheId", getCocheId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("marca", getMarca());
		attributes.put("modelo", getModelo());
		attributes.put("precio", getPrecio());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long CocheId = (Long)attributes.get("CocheId");

		if (CocheId != null) {
			setCocheId(CocheId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String marca = (String)attributes.get("marca");

		if (marca != null) {
			setMarca(marca);
		}

		String modelo = (String)attributes.get("modelo");

		if (modelo != null) {
			setModelo(modelo);
		}

		Double precio = (Double)attributes.get("precio");

		if (precio != null) {
			setPrecio(precio);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getCocheId() {
		return _CocheId;
	}

	@Override
	public void setCocheId(long CocheId) {
		_CocheId = CocheId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getMarca() {
		if (_marca == null) {
			return StringPool.BLANK;
		}
		else {
			return _marca;
		}
	}

	@Override
	public void setMarca(String marca) {
		_columnBitmask = -1L;

		_marca = marca;
	}

	@JSON
	@Override
	public String getModelo() {
		if (_modelo == null) {
			return StringPool.BLANK;
		}
		else {
			return _modelo;
		}
	}

	@Override
	public void setModelo(String modelo) {
		_modelo = modelo;
	}

	@JSON
	@Override
	public Double getPrecio() {
		return _precio;
	}

	@Override
	public void setPrecio(Double precio) {
		_precio = precio;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				Coche.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Coche.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Coche toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Coche)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CocheImpl cocheImpl = new CocheImpl();

		cocheImpl.setUuid(getUuid());
		cocheImpl.setCocheId(getCocheId());
		cocheImpl.setCompanyId(getCompanyId());
		cocheImpl.setUserId(getUserId());
		cocheImpl.setUserName(getUserName());
		cocheImpl.setCreateDate(getCreateDate());
		cocheImpl.setModifiedDate(getModifiedDate());
		cocheImpl.setMarca(getMarca());
		cocheImpl.setModelo(getModelo());
		cocheImpl.setPrecio(getPrecio());

		cocheImpl.resetOriginalValues();

		return cocheImpl;
	}

	@Override
	public int compareTo(Coche coche) {
		int value = 0;

		value = getMarca().compareTo(coche.getMarca());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Coche)) {
			return false;
		}

		Coche coche = (Coche)obj;

		long primaryKey = coche.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CocheModelImpl cocheModelImpl = this;

		cocheModelImpl._originalUuid = cocheModelImpl._uuid;

		cocheModelImpl._originalCompanyId = cocheModelImpl._companyId;

		cocheModelImpl._setOriginalCompanyId = false;

		cocheModelImpl._setModifiedDate = false;

		cocheModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Coche> toCacheModel() {
		CocheCacheModel cocheCacheModel = new CocheCacheModel();

		cocheCacheModel.uuid = getUuid();

		String uuid = cocheCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			cocheCacheModel.uuid = null;
		}

		cocheCacheModel.CocheId = getCocheId();

		cocheCacheModel.companyId = getCompanyId();

		cocheCacheModel.userId = getUserId();

		cocheCacheModel.userName = getUserName();

		String userName = cocheCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			cocheCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			cocheCacheModel.createDate = createDate.getTime();
		}
		else {
			cocheCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			cocheCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			cocheCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		cocheCacheModel.marca = getMarca();

		String marca = cocheCacheModel.marca;

		if ((marca != null) && (marca.length() == 0)) {
			cocheCacheModel.marca = null;
		}

		cocheCacheModel.modelo = getModelo();

		String modelo = cocheCacheModel.modelo;

		if ((modelo != null) && (modelo.length() == 0)) {
			cocheCacheModel.modelo = null;
		}

		cocheCacheModel.precio = getPrecio();

		return cocheCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", CocheId=");
		sb.append(getCocheId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", marca=");
		sb.append(getMarca());
		sb.append(", modelo=");
		sb.append(getModelo());
		sb.append(", precio=");
		sb.append(getPrecio());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("coche.crud.sb.model.Coche");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>CocheId</column-name><column-value><![CDATA[");
		sb.append(getCocheId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>marca</column-name><column-value><![CDATA[");
		sb.append(getMarca());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modelo</column-name><column-value><![CDATA[");
		sb.append(getModelo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>precio</column-name><column-value><![CDATA[");
		sb.append(getPrecio());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Coche.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Coche.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _CocheId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _marca;
	private String _modelo;
	private Double _precio;
	private long _columnBitmask;
	private Coche _escapedModel;
}